version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env

  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80

  database:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:5.0.7
    volumes:
      - redis_data:/data

  sidekiq:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  node_modules:
  postgres_data:
  redis_data:
